# Site settings
title: Kostas Ferles
email: kferles@cs.utexas.edu
url: https://kferles.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/kferles
  - title: bitbucket
    url: https://bitbucket.org/kferles/
  - title: linkedin
    url: https://gr.linkedin.com/pub/kostas-ferles/66/3b2/911
  - title: facebook
    url: https://www.facebook.com/kferles

# Build settings
markdown: kramdown
permalink: pretty
